name: CI Pipeline

on:
  push:
    branches:
      - dev-webscraping

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.2'  # Assure-toi que cette version est installée

      - name: Clean and Create Build Directory
        run: |
          if exist build (
            rmdir /s /q build
          )
          mkdir build

      - name: Configure Project
        run: |
          cd build
          cmake -G "Visual Studio 17 2022" -A Win64 ..  # Assure-toi que Win64 est correct

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release  # ou Debug selon ce que tu veux

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure  # Exécute les tests
