name: C++ CI

on:
  push:
    branches:
      - dev-webscraping

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1.2

    - name: Set up Visual Studio 2022
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat

    - name: Install GoogleTest
      run: |
        ./vcpkg/vcpkg install gtest

    - name: List files
      run: dir

    - name: Build Solution
      run: |
        msbuild ./DateQuest.sln /p:Configuration=Debug /p:Platform=x64

    - name: Run Unit Tests
      run: |
        .\path\to\test\executable\tests.exe

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: path/to/test/results
