name: CI Pipeline

on:
  push:
    branches:
      - dev-webscraping

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.2'  # Remplace par ta version de CMake

      - name: Configure Project
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win64 ..  # Supprime -DCMAKE_CONFIGURATION_TYPES

      - name: Build Project
        run: |
          cmake --build . --config Release  # Changez en Debug si nécessaire

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure  # Exécute les tests
