name: CI Pipeline test

on:
    push:
        branch:
            - dev-webscraping

jobs:
    build:
        runs-on: windows-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Cmake
              uses: jwlawson/actions-setup-cmake@v1
              with:
                cmake-version: '3.21.2'
            
            - name: Configure Project
              run: |
                mkdir build
                cd build
                cmake -G "Visual Studio 17 2022" -A Win64 ..
            
            - name: Build Project
              run: |
                cd build
                ctest --output-on-fealure # Execute tests and display result if echec