name: C++ CI

on:
  push:
    branches:
      - dev-webscraping

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1.2

    - name: Set up Visual Studio 2022
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat

    - name: Install GoogleTest
      run: |
        ./vcpkg/vcpkg install gtest

    - name: List files
      run: dir

    - name: Install NuGet
      run: choco install nuget.commandline

    - name: Restore NuGet packages
      run: nuget restore ./DateQuest.sln

    - name: Build Solution
      run: |
        msbuild ./DateQuest.sln /p:Configuration=Debug /p:Platform=x64

    - name: Run Unit Tests
      run: |
        cd WebscrapingClient
        msbuild WebscrapingClient.vcxproj /p:Configuration=Debug /p:Platform=x64
        msbuild WebscrapingClient.vcxproj /p:Configuration=Debug /p:Platform=x64
        x64\Debug\WebscrapingClient.exe

